<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>demo_158</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Fonts\Dirooz.ttf" />
    <None Remove="Images\account-circle-outline.svg" />
    <None Remove="Images\blue profile.png" />
    <None Remove="Images\CancelButton.png" />
    <None Remove="Images\DefualtUserPicture.png" />
    <None Remove="Images\icons8-send-100.png" />
    <None Remove="Images\OkButton.png" />
    <None Remove="Images\Picture.jpg" />
    <None Remove="Media\loading.mp4" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Media\loading.mp4">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\blue profile.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FontAwesome.WPF" Version="4.7.0.9" />
    <PackageReference Include="MahApps.Metro" Version="2.4.11" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="websocketsharp.core" Version="1.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Fonts\AOrdibeheshtshablon.TTF" />
    <Resource Include="Fonts\Dirooz.ttf">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Images\account-circle-outline.svg" />
    <Resource Include="Images\CancelButton.png" />
    <Resource Include="Images\DefualtUserPicture.png" />
    <Resource Include="Images\icons8-send-100.png" />
    <Resource Include="Images\OkButton.png" />
    <Resource Include="Images\Picture.jpg" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="AssemblyInfo.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
